sudo: required

language: python

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv run flake8
  - pipenv check
  - pipenv run pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - master
